'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, Check, ChevronDown, Download, Film, Gauge, Layers3, Link2, Loader2, MessageSquareText, Mic2, Moon, Play, Redo2, RotateCcw, Scissors, Settings2, Sparkles, Sun, Undo2, Upload, WandSparkles, X } from 'lucide-react'

type EditState = { brightness: number; contrast: number; sharpness: number; mirror: boolean; zoom: boolean; captions: boolean; captionStyle: 'bold' | 'minimal' }
const initial: EditState = { brightness: 100, contrast: 100, sharpness: 100, mirror: false, zoom: false, captions: true, captionStyle: 'bold' }

export default function ShortsStudio() {
  const [url, setUrl] = useState('')
  const [status, setStatus] = useState<'idle' | 'analyzing' | 'ready' | 'exporting'>('idle')
  const [edit, setEdit] = useState(initial)
  const [past, setPast] = useState<EditState[]>([])
  const [future, setFuture] = useState<EditState[]>([])
  const [activeTab, setActiveTab] = useState<'visual' | 'captions'>('visual')
  const [playing, setPlaying] = useState(false)
  const [caption, setCaption] = useState('لا تنتظر اللحظة المثالية، اصنعها الآن')

  const update = (patch: Partial<EditState>) => { setPast((p) => [...p, edit]); setFuture([]); setEdit({ ...edit, ...patch }) }
  const undo = () => { const previous = past.at(-1); if (!previous) return; setFuture((f) => [edit, ...f]); setEdit(previous); setPast((p) => p.slice(0, -1)) }
  const redo = () => { const next = future[0]; if (!next) return; setPast((p) => [...p, edit]); setEdit(next); setFuture((f) => f.slice(1)) }
  const analyze = async () => { setStatus('analyzing'); try { const res = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) }); const data = await res.json(); if (data.caption) setCaption(data.caption); } catch {} setTimeout(() => setStatus('ready'), 900) }
  const exportVideo = async () => { setStatus('exporting'); try { const res = await fetch('/api/export', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url, edit }) }); const data = await res.json(); if (data.downloadUrl) window.open(data.downloadUrl, '_blank'); } catch {} setTimeout(() => setStatus('ready'), 1200) }
  const previewStyle = useMemo(() => ({ filter: `brightness(${edit.brightness}%) contrast(${edit.contrast}%) saturate(${edit.sharpness}%)`, transform: `${edit.mirror ? 'scaleX(-1)' : ''} ${edit.zoom ? 'scale(1.15)' : ''}` }), [edit])

  return <main dir="rtl" className="studio-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><span>مِقطع</span><small>AI SHORTS</small></div><nav><button className="nav-active"><Layers3 size={16} /> الاستوديو</button><button><Film size={16} /> مشاريعي</button><button><Gauge size={16} /> الاستخدام</button></nav><div className="top-actions"><button className="icon-btn" aria-label="الوضع الليلي"><Moon size={17} /></button><div className="avatar">م</div></div></header>
    <section className="workspace">
      <aside className="sidebar"><div className="side-title"><span>مشروع جديد</span><button className="icon-btn"><Settings2 size={17} /></button></div><div className="project-card"><div className="project-thumb"><Play size={18} fill="currentColor" /></div><div><strong>فيديو جديد</strong><span>لم يتم التحليل بعد</span></div><ChevronDown size={15} /></div><div className="side-section"><span>خطوات العمل</span><div className="step done"><Check size={15} /><div><b>مصدر الفيديو</b><small>رابط يوتيوب</small></div></div><div className={`step ${status !== 'idle' ? 'done' : 'current'}`}><Scissors size={15} /><div><b>القص الذكي</b><small>اكتشاف اللحظات</small></div></div><div className="step current"><WandSparkles size={15} /><div><b>التحرير والتصدير</b><small>تخصيص المقطع</small></div></div></div><div className="side-footer"><div className="pro-note"><Sparkles size={16} /><div><b>مِقطع Pro</b><small>تصدير بدقة 1080p</small></div></div></div></aside>
      <section className="main-panel"><div className="welcome-row"><div><p className="eyebrow">استوديو صناعة الشورتس</p><h1>حوّل أي فيديو إلى <em>مقطع يستحق المشاهدة.</em></h1><p className="lead">أدخل رابط يوتيوب، ودع الذكاء الاصطناعي يكتشف أفضل لحظاته لك.</p></div><div className="quality-pill"><span className="live-dot" /> جودة التصدير <b>1080p</b></div></div>
        <div className="url-card"><div className="url-label"><Link2 size={17} /><span>رابط فيديو يوتيوب</span><small>يدعم المقاطع العامة فقط</small></div><div className="url-input"><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://youtube.com/watch?v=..." dir="ltr" /><button onClick={analyze} disabled={status === 'analyzing' || !url}>{status === 'analyzing' ? <><Loader2 className="spin" size={17} /> جارٍ التحليل...</> : <><Sparkles size={17} /> تحليل ذكي</>}</button></div></div>
        <div className="editor-grid"><div className="preview-column"><div className="section-heading"><div><h2>المعاينة المباشرة</h2><span>9:16 · عمودي</span></div><div className="history"><button onClick={undo} disabled={!past.length} aria-label="تراجع"><Undo2 size={17} /></button><button onClick={redo} disabled={!future.length} aria-label="إعادة"><Redo2 size={17} /></button></div></div><div className="phone-frame"><div className="video-canvas"><div className="video-art" style={previewStyle}><div className="art-sun" /><div className="art-person" /><div className="art-ground" /></div><div className="video-overlay"><span className="clip-time">00:12 / 00:21</span><span className="no-watermark">بدون علامة مائية</span></div>{edit.captions && <div className={`caption ${edit.captionStyle}`}>{caption}<small>NEVER SETTLE</small></div>}<button className="play-button" onClick={() => setPlaying(!playing)} aria-label={playing ? 'إيقاف' : 'تشغيل'}>{playing ? <span className="pause-bars" /> : <Play size={25} fill="currentColor" />}</button><div className="timeline"><span style={{ width: playing ? '58%' : '42%' }} /></div></div></div><div className="preview-meta"><span><span className="green-dot" /> تم التحليل · أفضل لحظة</span><span>مدة المقطع <b>00:21</b></span></div></div>
          <div className="controls-column"><div className="tabs"><button className={activeTab === 'visual' ? 'tab-active' : ''} onClick={() => setActiveTab('visual')}><Sun size={16} /> تحسين بصري</button><button className={activeTab === 'captions' ? 'tab-active' : ''} onClick={() => setActiveTab('captions')}><MessageSquareText size={16} /> النصوص والكابتشن</button></div>{activeTab === 'visual' ? <div className="control-body"><Control label="الإضاءة" value={edit.brightness} onChange={(v) => update({ brightness: v })} /><Control label="التباين" value={edit.contrast} onChange={(v) => update({ contrast: v })} /><Control label="الحدة" value={edit.sharpness} onChange={(v) => update({ sharpness: v })} /><div className="toggle-row"><div><b>عكس أفقي</b><small>Mirror الفيديو</small></div><button className={`toggle ${edit.mirror ? 'on' : ''}`} onClick={() => update({ mirror: !edit.mirror })}><span /></button></div><div className="toggle-row"><div><b>تكبير ذكي</b><small>Zoom In · 15%</small></div><button className={`toggle ${edit.zoom ? 'on' : ''}`} onClick={() => update({ zoom: !edit.zoom })}><span /></button></div></div> : <div className="control-body"><label className="field-label">النص الظاهر على الفيديو</label><textarea value={caption} onChange={(e) => { setPast((p) => [...p, edit]); setCaption(e.target.value) }} rows={3} /><div className="toggle-row"><div><b>إظهار الكابتشن</b><small>عربي + English</small></div><button className={`toggle ${edit.captions ? 'on' : ''}`} onClick={() => update({ captions: !edit.captions })}><span /></button></div><label className="field-label">النمط</label><div className="style-options"><button className={edit.captionStyle === 'bold' ? 'selected' : ''} onClick={() => update({ captionStyle: 'bold' })}>Bold <small>واضح ومتحرك</small></button><button className={edit.captionStyle === 'minimal' ? 'selected' : ''} onClick={() => update({ captionStyle: 'minimal' })}>Minimal <small>بسيط وأنيق</small></button></div><div className="language-row"><button className="language active">العربية</button><button className="language">English</button><button className="language"><Mic2 size={14} /> تلقائي</button></div></div>}<div className="export-area"><div><b>جاهز للتصدير؟</b><small>سيتم إنشاء ملف MP4 بدقة 1080p</small></div><button className="export-btn" onClick={exportVideo} disabled={status === 'exporting'}>{status === 'exporting' ? <><Loader2 className="spin" size={18} /> جارٍ التجهيز</> : <><Download size={18} /> تصدير وتنزيل</>}</button></div></div></div>
      </section>
    </section>
  </main>
}

function Control({ label, value, onChange }: { label: string; value: number; onChange: (v: number) => void }) { return <div className="range-control"><div><b>{label}</b><output>{value}%</output></div><input type="range" min="75" max="125" value={value} onChange={(e) => onChange(Number(e.target.value))} /></div> }
